version: '3'
services:
  rstm:
    container_name: rstm
    restart: always
    image: ghcr.io/rustamyusupov/rstm.me:master
    ports:
      - '80:80'
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug true --cleanup true --interval 30 rstm
