version: "3.3"
services:
  rstm:
    container_name: rstm
    restart: unless-stopped
    image: ghcr.io/rustamyusupov/rstm.me:master
    networks:
      - traefik_rstm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.rstm.entrypoints=web,websecure"
      - "traefik.http.routers.rstm.rule=Host(`rstm.me`)"
      - "traefik.http.routers.rstm.tls=true"
      - "traefik.http.services.rstm.loadbalancer.server.port=8080"
      - "traefik.http.routers.rstm.tls.certresolver=letsEncrypt"
  wishes-front:
    container_name: wishes-front
    restart: unless-stopped
    image: ghcr.io/rustamyusupov/wishes-front:main
    networks:
      - traefik_rstm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.wishes-front.entrypoints=web,websecure"
      - "traefik.http.routers.wishes-front.rule=Host(`rstm.me`) && PathPrefix(`/wishes`)"
      - "traefik.http.routers.wishes-front.tls=true"
      - "traefik.http.services.wishes-front.loadbalancer.server.port=8080"
      - "traefik.http.routers.wishes-front.tls.certresolver=letsEncrypt"
  wishes-back:
    container_name: wishes-back
    restart: unless-stopped
    image: ghcr.io/rustamyusupov/wishes-back:main
    volumes:
      - ~/db.json:/app/dist/db.json
    networks:
      - traefik_rstm
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.wishes-back.entrypoints=web,websecure"
      - "traefik.http.routers.wishes-back.rule=Host(`rstm.me`) && PathPrefix(`/api`)"
      - "traefik.http.routers.wishes-back.tls=true"
      - "traefik.http.services.wishes-back.loadbalancer.server.port=9000"
      - "traefik.http.routers.wishes-back.tls.certresolver=letsEncrypt"
  traefik:
    container_name: "traefik"
    restart: unless-stopped
    image: "traefik:v2.10"
    networks:
      - traefik_rstm
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsEncrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsEncrypt.acme.email=i@rstm.me"
      - "--certificatesresolvers.letsEncrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug true --cleanup true --interval 30 rstm wishes-front wishes-back

networks:
  traefik_rstm:
